version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw@rd
      - POSTGRES_DB=CHU
    ports:
      - "5434:5434"
