server:
  port: 9091
spring:
  application:
    name: CHU
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/CHU?serverTimezone=UTC
    username: postgres
    password: Passw@rd
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
